#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="${PROOF_SHORTIO_PROJECT_DIR:-${PROJECT_ROOT:-$HOME}/proof-shortio-airtable}"
RUN_SHORTLINK="$(dirname "$0")/run-proof-shortlink.sh"
TITLE=""
MARKDOWN_FILE=""
CUSTOM_SLUG=""
DRY_RUN="false"
KEEP_DEBUG="false"

usage() {
  cat >&2 <<'USAGE'
Usage: create-proof-and-shortlink.sh --title "Document title" --markdown-file /absolute/path.md [--slug custom-path] [--dry-run]

Creates a Proof document from Markdown, creates or reuses a Short.io link on ${SHORT_IO_DOMAIN}, writes Airtable, and prints a human-readable result.

Required environment variables:
  SHORT_IO_DOMAIN       Your Short.io custom domain
  SHORT_IO_API_KEY      Your Short.io API key
  AIRTABLE_BASE_ID      Your Airtable base ID
  AIRTABLE_TABLE_ID     Your Airtable table ID
  AIRTABLE_API_KEY      Your Airtable personal access token
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --title)
      TITLE="${2:-}"
      shift 2
      ;;
    --markdown-file)
      MARKDOWN_FILE="${2:-}"
      shift 2
      ;;
    --slug|--path)
      CUSTOM_SLUG="${2:-}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN="true"
      shift
      ;;
    --keep-debug)
      KEEP_DEBUG="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 64
      ;;
  esac
done

if [[ -z "$MARKDOWN_FILE" ]]; then
  echo "Missing --markdown-file." >&2
  usage
  exit 64
fi

if [[ ! -f "$MARKDOWN_FILE" ]]; then
  echo "Markdown file not found: $MARKDOWN_FILE" >&2
  exit 66
fi

if [[ "$MARKDOWN_FILE" != /* ]]; then
  echo "Use an absolute path for --markdown-file." >&2
  exit 64
fi

if [[ -z "$TITLE" ]]; then
  TITLE="$(python3 - "$MARKDOWN_FILE" <<'PY'
from pathlib import Path
import sys
p = Path(sys.argv[1])
text = p.read_text(errors='replace')
for line in text.splitlines():
    if line.startswith('# '):
        print(line[2:].strip())
        break
else:
    print(p.stem.replace('-', ' ').replace('_', ' ').strip().title() or 'Untitled Proof Document')
PY
)"
fi

if [[ -z "$TITLE" ]]; then
  echo "Title could not be determined." >&2
  exit 64
fi

if [[ "$DRY_RUN" == "true" ]]; then
  echo "Status: Ready"
  echo "Title: $TITLE"
  echo "Markdown source: $MARKDOWN_FILE"
  if [[ -n "$CUSTOM_SLUG" ]]; then
    echo "Shortlink path: ${SHORT_IO_DOMAIN}/${CUSTOM_SLUG#/}"
  else
    echo "Shortlink path: generated by Short.io"
  fi
  echo "No Proof document, Short.io link, or Airtable row was created because --dry-run was used."
  exit 0
fi

if [[ ! -x "$RUN_SHORTLINK" ]]; then
  echo "Shortlink runner is not executable or missing: $RUN_SHORTLINK" >&2
  exit 78
fi

workdir="$(mktemp -d "${TMPDIR:-/tmp}/proof-create-shortlink.XXXXXX")"
cleanup() {
  if [[ "$KEEP_DEBUG" != "true" ]]; then
    rm -rf "$workdir"
  else
    echo "Debug files retained at: $workdir" >&2
  fi
}
trap cleanup EXIT

proof_json="$workdir/proof-create.json"
short_stdout="$workdir/shortlink-stdout.json"
short_stderr="$workdir/shortlink-stderr.log"

PROOF_TITLE="$TITLE" MARKDOWN_FILE="$MARKDOWN_FILE" PROOF_CREATE_JSON="$proof_json" python3 <<'PY'
from pathlib import Path
import json
import os
import sys
import urllib.error
import urllib.request

title = os.environ['PROOF_TITLE']
markdown_path = Path(os.environ['MARKDOWN_FILE'])
out_path = Path(os.environ['PROOF_CREATE_JSON'])
markdown = markdown_path.read_text(errors='replace')
payload = json.dumps({'title': title, 'markdown': markdown}).encode()
req = urllib.request.Request(
    'https://www.proofeditor.ai/share/markdown',
    data=payload,
    headers={'Content-Type': 'application/json', 'Accept': 'application/json'},
    method='POST',
)
try:
    with urllib.request.urlopen(req, timeout=60) as resp:
        body = resp.read().decode()
        status = resp.status
except urllib.error.HTTPError as exc:
    body = exc.read().decode(errors='replace')
    print(f'Proof document creation failed with HTTP {exc.code}.', file=sys.stderr)
    print(body[:800], file=sys.stderr)
    sys.exit(1)
except Exception as exc:
    print(f'Proof document creation failed: {exc}', file=sys.stderr)
    sys.exit(1)

try:
    data = json.loads(body)
except json.JSONDecodeError:
    print('Proof document creation returned non-JSON response.', file=sys.stderr)
    print(body[:800], file=sys.stderr)
    sys.exit(1)

token_url = data.get('tokenUrl') or data.get('tokenURL') or data.get('shareUrl') or data.get('url')
slug = data.get('slug') or data.get('docId') or data.get('id')
if not token_url or 'token=' not in token_url:
    print('Proof document creation did not return a tokenized URL.', file=sys.stderr)
    safe = {k: v for k, v in data.items() if k not in {'accessToken', 'ownerSecret', 'token', 'shareToken'}}
    print(json.dumps(safe, indent=2)[:1200], file=sys.stderr)
    sys.exit(1)

out_path.write_text(json.dumps({'title': title, 'tokenUrl': token_url, 'slug': slug, 'raw': data}))
PY

token_url="$(python3 - "$proof_json" <<'PY'
from pathlib import Path
import json, sys
print(json.loads(Path(sys.argv[1]).read_text())['tokenUrl'])
PY
)"
proof_safe_url="$(python3 - "$proof_json" <<'PY'
from pathlib import Path
import json, sys
from urllib.parse import urlsplit, urlunsplit
url = json.loads(Path(sys.argv[1]).read_text())['tokenUrl']
parts = urlsplit(url)
print(urlunsplit((parts.scheme, parts.netloc, parts.path, '', '')))
PY
)"

if [[ -n "$CUSTOM_SLUG" ]]; then
  export SHORT_IO_PATH="${CUSTOM_SLUG#/}"
fi

set +e
"$RUN_SHORTLINK" "$token_url" >"$short_stdout" 2>"$short_stderr"
short_status=$?
set -e

if [[ $short_status -ne 0 ]]; then
  echo "Proof document was created, but shortlink or Airtable tracking failed." >&2
  echo "Proof document: $proof_safe_url" >&2
  python3 - "$short_stderr" <<'PY' >&2
from pathlib import Path
import re, sys
text = Path(sys.argv[1]).read_text(errors='replace')
text = re.sub(r'(https://www\.proofeditor\.ai/d/[^?\s]+)\?token=[^\s"\']+', r'\1?token=[REDACTED]', text)
print(text[-1200:])
PY
  exit "$short_status"
fi

python3 - "$proof_json" "$short_stdout" <<'PY'
from pathlib import Path
import json
import sys
from urllib.parse import urlsplit, urlunsplit
proof = json.loads(Path(sys.argv[1]).read_text())
short = json.loads(Path(sys.argv[2]).read_text())

def safe_proof_url(url: str) -> str:
    parts = urlsplit(url)
    return urlunsplit((parts.scheme, parts.netloc, parts.path, '', ''))

print('Status: Complete')
print(f"Proof document: {safe_proof_url(proof['tokenUrl'])}")
print(f"Shortlink: {short['shortUrl']}")
print(f"Airtable record: {short['recordId']}")
print(f"Title: {short.get('title') or proof['title']}")
print('Verification: Proof document created, Short.io link created or reused, and Airtable row written or confirmed.')
PY
